version: '3.9'

services:

  #
  # AGGREGATORS
  #
  aggregator-telco-finder-1:
    build:
      context: ./aggregator/telco-finder
    environment:
      PORT: 2211
    ports:
      - 2211:2211

  aggregator-telco-finder-2:
    build:
      context: ./aggregator/telco-finder
    environment:
      PORT: 2222
    ports:
      - 2222:2222

  aggregator-telco-router-1:
    build:
      context: ./aggregator/telco-router
    environment:
      PORT: 3311
      TELCO_FINDER_HOST: aggregator-telco-finder-1
      DATABASE_HOST: "mongodb:27017"
      DATABASE_NAME: "aggregator-telco-router-1"
    ports:
      - 3311:3311

  aggregator-telco-router-2:
    build:
      context: ./aggregator/telco-router
    environment:
      PORT: 3322
      TELCO_FINDER_HOST: aggregator-telco-finder-2
      DATABASE_HOST: "mongodb:27017"
      DATABASE_NAME: "aggregator-telco-router-2"
    ports:
      - 3322:3322

  #
  # OPERATOR PLATFORMS
  #
  operator-platform-apigateway-1:
    image: kong:3.1.1-alpine
    user: kong
    environment:
      KONG_DATABASE: "off"
      KONG_PLUGINS: "bundled,log-signature"
      KONG_LUA_PACKAGE_PATH: "/opt/?.lua;;"
      KONG_DECLARATIVE_CONFIG: "/opt/kong/config-operator-1.yaml"
      KONG_LOG_LEVEL: "warn"
    ports:
      - 10000:8000
    volumes:
      - ./operator-platform/apigateway/config:/opt/kong
      - ./operator-platform/apigateway/plugins:/opt/kong/plugins
      - ./operator-platform/apigateway/logs:/opt/logs

  operator-platform-apigateway-2:
    image: kong:3.1.1-alpine
    user: kong
    environment:
      KONG_DATABASE: "off"
      KONG_PLUGINS: "bundled,log-signature"
      KONG_LUA_PACKAGE_PATH: "/opt/?.lua;;"
      KONG_DECLARATIVE_CONFIG: "/opt/kong/config-operator-2.yaml"
      KONG_LOG_LEVEL: "warn"
    ports:
      - 20000:8000
    volumes:
      - ./operator-platform/apigateway/config:/opt/kong
      - ./operator-platform/apigateway/plugins:/opt/kong/plugins
      - ./operator-platform/apigateway/logs:/opt/logs

  operator-platform-camara-apis-1:
    build:
      context: ./operator-platform/camara-apis
    environment:
      PORT: 8001
    ports:
      - 8001:8001

  operator-platform-camara-apis-2:
    build:
      context: ./operator-platform/camara-apis
    environment:
      PORT: 8002
    ports:
      - 8002:8002

  operator-platform-authserver-1:
    build:
      context: ./operator-platform/authserver
    depends_on:
      - mongodb
    environment:
      PORT: 9010
      HOST: "http://authserver-1:9010"
      DATABASE_HOST: "mongodb:27017"
      DATABASE_NAME: "authserver-telefonica"
      OPERATOR_ID: "TELEFONICA"
    ports:
      - 9010:9010

  operator-platform-authserver-2:
    build:
      context: ./operator-platform/authserver
    depends_on:
      - mongodb
    environment:
      PORT: 9020
      HOST: "http://authserver-2:9020"
      DATABASE_HOST: "mongodb:27017"
      DATABASE_NAME: "authserver-vodafone"
      OPERATOR_ID: "VODAFONE"
    ports:
      - 9020:9020

  #
  # MISC
  #
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    command: --quiet --logpath /dev/null
    volumes:
      - mongodbdata:/data/db

  mongo-seed:
    build:
      context: ./mongo-seed
    depends_on:
      - mongodb
      - operator-platform-authserver-1
      - operator-platform-authserver-2

  demo-sdk-example:
    build:
      context: .
    environment:
      PORT: 3000
      # Contracting Operator: TEF
      CAMARA_API_URL: 'http://operator-1:11111'
      CAMARA_AUTH_URL: 'http://authserver-1:9010/es/oauth2/authorize'
      CAMARA_ISSUER: '73902489-c201-4819-bdf9-3708a484fe21'
    ports:
      - 3000:3000
    volumes:
      - ./camara-node-sdk:/apps/camara-node-sdk
      - nm1:/apps/camara-node-sdk/node_modules
      - nm2:/apps/camara-node-sdk/examples/node_modules

volumes:
  mongodbdata:
  nm1:
  nm2:
